### ISSUE TITLE
Support Webpack v5

### ISSUE THREAD

**Issue by evenstensberg** [namics/webpack-config-plugins#68] opened 2019-11-12 18:20 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Does not work with webpack 5

## Expected behavior

Work with webpack 5

## Minimal reproduction of the problem with instructions

Create a webpack 5 project

## What is the motivation / use case for changing the behavior?

Improving webpack 

I'm going to fill this out properly

**Comment by nemchik** [comment] 2021-01-04 14:07
I also now realize i tagged this as fixing the wrong issue. It should be #18 . I will rebase to reword the commit and edit the PR title. My apologies.

**Comment by ernscht** [comment] 2021-04-22 06:25
duplicate of #55

**Closed by ernscht** 2021-04-22 06:25 UTC
Labels: upgrade
